# ===================================================================
# 开发工具时时默认的配置
#
# 所有相对路径以本项目根目录为准
# ===================================================================

generator:
  process:
    defaults:
      - laravel
      - laravel-doc
      - postman
      - testcases
      - openapi
    laravel-auto-test:
      - laravel-auto-test
    client:
      - nodejs-client
  env: dev
  api-prefix: api
  template-path: ./liberator-templates/main/java

  test-host: http://localhost

  generators:
    force-suffix: .example

    postman:
      path: ./output
    testcases:
      path: ./output/testcases

    laravel:
      path: ./output/laravel

      bo-suffix: BO
      bo-folder: BOs
      dto-suffix: DTO
      dto-folder: DTOs
      service-suffix: Service
      service-folder: Services
    laravel-doc:
      path: ./output/larecipe
      http-prefix: docs
    laravel-auto-test:
      path: ./output/tests
      force-replace: false
      testcases-path: ./output/testcases


    nodejs-client:
      output: ./output/nodejs-client
    java-client:
      path: ./output/java-client
      classpath:

spring:
  thymeleaf:
    mode: TEXT
    suffix: .stub
    encoding: UTF-8
    prefix: classpath:/stubs/
